#!/usr/bin/env python
# /// pyproject
# [run]
# dependencies = [
#   "ziglang==0.11.0"
# ]
# ///
import os
import subprocess
import sys


def flag_filter(flag: str) -> bool:
    # Workaround for <https://github.com/sfackler/rust-openssl/issues/2043>.
    if flag == "-latomic":
        return False

    if flag == "-lc":
        return False
    if flag == "-Wl,-melf_i386":
        return False
    if "self-contained" in flag and "crt" in flag:
        return False
    return True


def main():
    args = [flag for flag in sys.argv[1:] if flag_filter(flag)]

    # Disable atomics and use locks instead in OpenSSL.
    # Zig toolchains do not provide atomics.
    # This is a workaround for <https://github.com/deltachat/deltachat-core-rust/issues/4799>
    args += ["-DBROKEN_CLANG_ATOMICS"]

    subprocess.run(
        [
            sys.executable,
            "-m",
            "ziglang",
            "cc",
            *args,
        ],
        check=True,
    )


main()
